/**
 * Curated subset of lucide-react icons used by A/addin.
 *
 * Importing a lucide-react icon outside this allowlist is a lint error
 * (see eslint.config.js icon rule). Add icons here when a new component
 * needs one — don't reach for marketing/illustration icons.
 */
export {
  Activity,
  AlertTriangle,
  Archive,
  ArrowDown,
  ArrowRight,
  ArrowUp,
  Box,
  Calendar,
  Check,
  ChevronDown,
  ChevronRight,
  Circle,
  Clock,
  Code,
  Copy,
  Database,
  Dot,
  Download,
  Eye,
  EyeOff,
  FileText,
  Folder,
  GitBranch,
  Hash,
  Inbox,
  Info,
  Lock,
  Menu,
  MessageSquare,
  Minus,
  MoreHorizontal,
  Pause,
  Play,
  Plus,
  RotateCw,
  Search,
  Settings,
  Shield,
  Square,
  Terminal,
  Trash,
  Unlock,
  Wrench,
  X,
  Zap,
} from "lucide-react";
